### ISSUE TITLE
project config file (possibly) not being read

### ISSUE THREAD

**Issue by sga-13** [tekumara/typos-lsp#109]
I am trying to to get 2 word corrections to be ignored, and they are not working, and I do not know why. I have a file named `.typos.toml` (I have also tried `_typst.toml`), all I want is 

```
[default.extend-words]
ket = "ket"
braket = "braket"
```

(my notes have like billion kets, so it is a bit annoying)

i also tried to reference config given on the typos readme

```
[default]
extend-ignore-identifiers-re = [
    # *sigh* this just isn't worth the cost of fixing
    "AttributeID.*Supress.*",
]

[default.extend-identifiers]
# *sigh* this just isn't worth the cost of fixing
AttributeIDSupressMenu = "AttributeIDSupressMenu"

[default.extend-words]
# Don't correct the surname "Teh"
teh = "teh"
```

I tried adding teh to the file, and it still flagged. I have tried restarting all my editor instances, other lsps do work correctly (for example, stuff compiles to correct dir)

**Comment by tekumara** [comment]
Could you share the debug level logs from typos-lsp?

**Comment by sga-13** [comment]
[helix.log](https://github.com/user-attachments/files/17003511/helix.log)

I am sorry how to get logs specific to typos lsp, i have attached the helix log file, also relevant part of helix config

```
[language-server.typos]
command = "typos-lsp"
environment = {"RUST_LOG" = "error"}

[language-server.typos.config]
diagnosticSeverity = "Hint"
```

for now I have added 
```
[language-server.typos.config]
...
config = "~/.config/helix/typos.toml"
```
which does work and is good enough for me, so i am closing my issue for now.

Thank you for the LSP, it is genuinely a godsend
