### ISSUE TITLE
Would it be possible to use an older glibc?

### ISSUE THREAD

**Issue by darkvertex** [tekumara/typos-lsp#112]
I can't use `typos-lsp` remotely (via VSCode's Remote Host extension) on my employer Linux machines because they're on RockyLinux 8 which uses glibc-2.28.236 but `typos-lsp` from you needs glibc 2.29:

```
> ldd ./typos-lsp
./typos-lsp: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./typos-lsp)
        linux-vdso.so.1 (0x00007fffccbf1000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f81108d2000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f81106b2000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f8110330000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f811012c000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f810fd67000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f8111bce000)
```

Any chance you could make the Linux executable more broadly compatible? Statically compile it maybe? Or require an older glibc?

**Comment by tekumara** [comment]
Happy to add a [tier 2 musl build](https://doc.rust-lang.org/rustc/platform-support.html#tier-2-with-host-tools) to support this - are you using arm64 or x86_64?

**Comment by tekumara** [comment]
Happy to add a [tier 2 musl build](https://doc.rust-lang.org/rustc/platform-support.html#tier-2-with-host-tools) to support this - are you using aarch64 or x86_64?

**Comment by darkvertex** [comment]
Hey, are we sure v0.1.24 released okay? It only has source code in the "Assets" of the release:
https://github.com/tekumara/typos-lsp/releases/tag/v0.1.24
vs say the release before that, which has many executables ready for download:
https://github.com/tekumara/typos-lsp/releases/tag/v0.1.23

**Comment by tekumara** [comment]
Oops - I'll have to investigate why I didn't get notified for that. Cutting a new 0.1.25 release now.

**Comment by darkvertex** [comment]
Thanks for the quick fix! I confirm the new "unknown-linux-musl" build runs where the old one wouldn't. Cool. :)

That said, the one bundled is still the one requiring glibc 2.29. I added the statically compiled `typos-lsp` executable in my PATH to no avail.

How can I point the extension to the good executable? I looked for a custom preference to override the path but there doesn't appear to be one.

**Comment by tekumara** [comment]
Try the setting `typos.path`.

It may make sense to bundle the musl binary with the VS Code extension if the memory hit isn't too bad.

**Comment by darkvertex** [comment]
Setting `typos.path` worked, thank you :)

**Comment by tekumara** [comment]
The latest release now bundles the musl binary so you can unset `typos.path` and just use the bundled version.

**Comment by darkvertex** [comment]
Wonderful! Thanks dude.
