### ISSUE TITLE
 'Typos spell checker' extension is not available in Code - OSS for Alpine Linux 64 bit. 

### ISSUE THREAD

**Issue by andar1an** [tekumara/typos-lsp#132]
May be nice to make this available on Alpine and other musl based distros. Target example is x86_64-unknown-linux-musl. 

I haven't looked at code, just noticed this today.

**Comment by tekumara** [comment]
There’s already a musl binary available, does it not work for you?

**Comment by tekumara** [comment]
See https://github.com/tekumara/typos-lsp/issues/112

**Comment by andar1an** [comment]
Oh interesting, maybe alpine is just not enabled in as platform specific extension? I do how open vsix works or vscode store, I am moving away from. Ide's but noticed this today.

**Comment by andar1an** [comment]
![Uploading 1731107973-wayshot.png…](Screenshot of Code-OSS)

**Comment by andar1an** [comment]
![1731107973-wayshot](https://github.com/user-attachments/assets/0b2cb81a-657a-4ba4-ba55-afa5e6049f6a)

See screenshot, I don't think this is the same as linked issue.

**Comment by tekumara** [comment]
Ah so it looks like there is a specific `alpine-x64` target, distinct from `linux-x64` (which is the musl binary):

```
❯ npx vsce publish --help
Usage: vsce publish [options] [version]

Publishes an extension

Options:
  -p, --pat <token>                Personal Access Token (defaults to VSCE_PAT environment variable)
  --azure-credential               Use Microsoft Entra ID for authentication
  -t, --target <targets...>        Target architectures. Valid targets: win32-x64, win32-arm64, linux-x64, linux-arm64, linux-armhf, darwin-x64, darwin-arm64, alpine-x64,
                                   alpine-arm64, web
```
This is for publishing to the vscode marketplace but I expect open-vsx is the same.

**Comment by tekumara** [comment]
This has now been published to [open vsx](https://open-vsx.org/extension/tekumara/typos-vscode) as an Alpine Linux 64 bit package.

**Comment by tekumara** [comment]
This has now been published to the [open vsx registry](https://open-vsx.org/extension/tekumara/typos-vscode) as an Alpine Linux 64 bit package. Hopefully that works for you.

**Comment by andar1an** [comment]
I can check tmr and update you if still seeing error, ty.
