### ISSUE TITLE
Instructions for running in Helix

### ISSUE THREAD

**Issue by sbromberger** [tekumara/typos-lsp#61]
For information (and possibly an update to the readme):

I got this working properly in [Helix](https://helix-editor.com) with the following configuration in `languages.toml`:

```
[language-server.typos]                                                                                               
environment = {"RUST_LOG" = "info"} 
command = "typos-lsp"              
config.diagnosticSeverity = "Warning"
```

Without overriding the `diagnosticSeverity` the format used is `ui.cursor`. When the severity is explicitly specified, it will use the standard helix diagnostic formats.

(Thanks for making this LSP! It's really great. I wish there were some way to add words to a custom dictionary, but I'm not sure how hard that would be.)

**Comment by tekumara** [comment]
Thanks for the suggestion I've now added [helix config here](https://github.com/tekumara/typos-lsp/blob/main/docs/helix-config.md).

PS: If you don't want certain words to be corrected, add them to typos.toml [like this](https://github.com/crate-ci/typos?tab=readme-ov-file#false-positives). You can do the opposite too - ie: add corrections that typos doesn't yet know about.
