### ISSUE TITLE
Broken v1.20.0 release

### ISSUE THREAD

**Issue by insomnes** [tekumara/typos-lsp#90]
Hi!
Sorry if it was answered before, can't find any related issue. It's minor but breaks my automated update flow.

I believe v1.20.0 pipeline in github failed, so the release was broken, and it happened with some of the previous releases too.
I am not very familiar with github workflow, but maybe there is a way to not publish on a failed build? 

Thank you!

**Comment by tekumara** [comment]
Thanks for raising this! I hadn't noticed. I've now enabled notifications for failed workflows.

I haven't found a good way yet of creating the Github release with nice release notes after a successful build.

**Comment by insomnes** [comment]
Thank you for the quick fix! Cool that you will have visibility now. I hope this will help.
